#include "ManagedCodeBuilder.hpp"

#include <devex/core/File.hpp>
#include <devex/core/Log.hpp>
#include <devex/core/Path.hpp>

#include <algorithm>
#include <array>
#include <format>
#include <system_error>
#include <thread>
#include <utility>

namespace devex::runtime::detail {
namespace {

using namespace std::chrono_literals;

constexpr auto checkInterval = 500ms;
// Editors often save in several steps: a build starts once the folder has been quiet this long.
constexpr auto settleTime = 300ms;

constexpr std::string_view projectTemplate = R"(<!-- Generated by the Devex editor: it is rewritten at every build. -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Game.Scripts</AssemblyName>
    <RootNamespace>{0}</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Deterministic>true</Deterministic>
    <!-- The engine build whose C# API the code uses, and the views of the project's C++ components.
         The editor sets both when it builds; these are for code editors. -->
    <DevexManagedDirectory Condition="'$(DevexManagedDirectory)' == ''">{1}</DevexManagedDirectory>
    <DevexGeneratedDirectory Condition="'$(DevexGeneratedDirectory)' == ''">{2}</DevexGeneratedDirectory>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**/*.cs" />
    <!-- The views of the game's C++ components, which the editor generates when they are built. -->
    <Compile Include="$(DevexGeneratedDirectory)/*.cs" />
  </ItemGroup>

  <ItemGroup>
    <!-- The engine's C# API, which the editor and the player already have loaded. -->
    <Reference Include="Devex.Managed">
      <HintPath>$(DevexManagedDirectory)/Devex.Managed.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
)";

constexpr std::string_view scriptTemplate = R"(using Devex;

// A component written in C#: its public fields are edited in the inspector and saved in scenes,
// and Update runs every frame for each entity that has it.
public class {0} : Component
{{
    // In radians per second.
    [Angle]
    public float Speed = 1.0f;

    public override void Start()
    {{
        Log.Info($"{0} starts on {{Scene.Name(Entity)}}");
    }}

    public override void Update(float delta)
    {{
        Transform.Rotation = Quat.AngleAxis(Speed * delta, Vec3.Up) * Transform.Rotation;
    }}
}}
)";

[[nodiscard]] bool contains(std::string_view text, std::string_view part)
{
    return text.find(part) != std::string_view::npos;
}

[[nodiscard]] std::filesystem::path buildDirectory(const asset::Project& project)
{
    return project.cacheDirectory() / "code" / "csharp";
}

} // namespace

std::filesystem::path ManagedCodeBuilder::assemblyPath(const asset::Project& project)
{
    return buildDirectory(project) / "bin" / "Game.Scripts.dll";
}

std::filesystem::path ManagedCodeBuilder::generatedDirectory(const asset::Project& project)
{
    return buildDirectory(project) / "generated";
}

std::filesystem::path ManagedCodeBuilder::builtAssembly() const
{
    return m_target.buildDirectory / "bin" / "Game.Scripts.dll";
}

bool ManagedCodeBuilder::hasCode(const asset::Project& project)
{
    std::error_code error;
    for (std::filesystem::recursive_directory_iterator entry(project.codeDirectory(), error), end; !error && entry != end;
         entry.increment(error))
    {
        if (entry->is_regular_file(error) && entry->path().extension() == ".cs")
        {
            return true;
        }
    }
    return false;
}

core::Result<std::filesystem::path> ManagedCodeBuilder::createScript(const asset::Project& project,
                                                                     std::string_view componentName)
{
    std::filesystem::path file = project.codeDirectory() / core::pathFromUtf8(std::string(componentName) + ".cs");
    std::error_code error;
    if (std::filesystem::exists(file, error))
    {
        return core::makeError(core::ErrorCode::AlreadyExists, "'{}' already exists", core::toUtf8(file.filename()));
    }
    if (core::Result<void> written = core::writeTextFile(file, std::format(scriptTemplate, componentName)); !written)
    {
        return std::unexpected(written.error());
    }
    return file;
}

ManagedCodeBuilder::ManagedCodeBuilder(asset::Project project, std::filesystem::path devexManagedDirectory,
                                       std::optional<Target> target)
    : m_project(std::move(project))
    , m_managedDirectory(std::move(devexManagedDirectory))
    , m_target(target.value_or(Target{.buildDirectory = buildDirectory(m_project),
                                      .generatedDirectory = generatedDirectory(m_project)}))
    , m_editorTarget(!target.has_value())
{
    m_sources = snapshotSources();
    std::error_code error;
    const std::filesystem::file_time_type built = std::filesystem::last_write_time(assemblyPath(m_project), error);
    // An engine rebuilt with another C# API needs the game compiled against it again.
    std::error_code apiError;
    const std::filesystem::file_time_type api =
        std::filesystem::last_write_time(m_managedDirectory / "Devex.Managed.dll", apiError);
    m_buildRequested = error || built < m_sources.newest || (!apiError && built < api);
}

bool ManagedCodeBuilder::needsBuild() const noexcept
{
    return m_buildRequested;
}

ManagedCodeBuilder::Snapshot ManagedCodeBuilder::snapshotSources() const
{
    Snapshot snapshot;
    std::error_code error;
    // The folders too: a file deleted while the editor was closed shows in the time of its folder.
    if (const std::filesystem::file_time_type folder = std::filesystem::last_write_time(m_project.codeDirectory(), error);
        !error)
    {
        snapshot.newest = folder;
    }
    for (std::filesystem::recursive_directory_iterator entry(m_project.codeDirectory(), error), end;
         !error && entry != end; entry.increment(error))
    {
        if (entry->is_directory(error))
        {
            snapshot.newest = std::max(snapshot.newest, entry->last_write_time(error));
        }
        else if (entry->is_regular_file(error) && entry->path().extension() == ".cs")
        {
            snapshot.newest = std::max(snapshot.newest, entry->last_write_time(error));
            ++snapshot.files;
        }
    }
    return snapshot;
}

void ManagedCodeBuilder::requestBuild() noexcept
{
    m_buildRequested = true;
}

ManagedCodeBuilder::State ManagedCodeBuilder::state() const noexcept
{
    return m_state;
}

const std::string& ManagedCodeBuilder::message() const noexcept
{
    return m_message;
}

core::Result<void> ManagedCodeBuilder::writeProjectFile() const
{
    const std::string name = m_project.name.empty() ? std::string("Game") : m_project.name;
    std::string root;
    for (const char character : name)
    {
        root.push_back(std::isalnum(static_cast<unsigned char>(character)) != 0 ? character : '_');
    }
    if (root.empty() || std::isdigit(static_cast<unsigned char>(root.front())) != 0)
    {
        root.insert(root.begin(), '_');
    }
    return core::writeTextFile(m_project.codeDirectory() / "Game.csproj",
                               std::format(projectTemplate, root, core::toUtf8(m_managedDirectory),
                                           core::toUtf8(generatedDirectory(m_project))));
}

bool ManagedCodeBuilder::update()
{
    const Clock::time_point now = Clock::now();
    if (now >= m_nextCheck)
    {
        m_nextCheck = now + checkInterval;
        if (Snapshot sources = snapshotSources(); sources != m_sources)
        {
            m_sources = sources;
            m_changedAt = now;
        }
    }
    if (m_changedAt && now - *m_changedAt >= settleTime)
    {
        m_changedAt.reset();
        m_buildRequested = true;
    }

    if (m_process)
    {
        for (const std::string& line : m_process->readLines())
        {
            if (std::optional<GameCodeBuilder::Diagnostic> diagnostic = GameCodeBuilder::parseDiagnostic(line))
            {
                m_diagnostics.push_back(std::move(*diagnostic));
            }
            const std::optional<bool> severity = GameCodeBuilder::severityOf(line);
            if (severity.value_or(false) || line.starts_with("error"))
            {
                DEVEX_LOG_ERROR("{}", line);
                if (m_message.empty())
                {
                    m_message = line;
                }
            }
            else if (severity == false)
            {
                DEVEX_LOG_WARNING("{}", line);
            }
            else if (!line.empty())
            {
                DEVEX_LOG_DEBUG("{}", line);
            }
        }
        if (const std::optional<int> exitCode = m_process->exitCode())
        {
            for (const std::string& line : m_process->readLines())
            {
                DEVEX_LOG_DEBUG("{}", line);
            }
            m_process.reset();
            finishBuild(*exitCode);
            return m_state == State::Succeeded;
        }
        return false;
    }

    if (m_buildRequested)
    {
        m_buildRequested = false;
        startBuild();
    }
    return false;
}

core::Result<void> ManagedCodeBuilder::buildAndWait()
{
    m_buildRequested = false;
    m_changedAt.reset();
    startBuild();
    while (m_process)
    {
        static_cast<void>(update());
        std::this_thread::sleep_for(std::chrono::milliseconds(20));
    }
    if (m_state != State::Succeeded)
    {
        return core::makeError(core::ErrorCode::InvalidState, "the C# code does not build: {}", m_message);
    }
    return {};
}

void ManagedCodeBuilder::startBuild()
{
    useEnglishDiagnostics();
    // The project file is the editor's: other builds only write it when it is missing.
    std::error_code error;
    if (m_editorTarget || !std::filesystem::exists(m_project.codeDirectory() / "Game.csproj", error))
    {
        if (core::Result<void> written = writeProjectFile(); !written)
        {
            m_state = State::Failed;
            m_message = written.error().message;
            DEVEX_LOG_ERROR("Cannot build the C# code: {}", written.error());
            return;
        }
    }
    // The build artifacts go to the cache of the project, next to its imported assets.
    const std::array<std::string, 11> arguments{
        "dotnet",
        "build",
        core::toUtf8(m_project.codeDirectory() / "Game.csproj"),
        "-c",
        "Release",
        "-o",
        core::toUtf8(m_target.buildDirectory / "bin"),
        std::format("-p:BaseIntermediateOutputPath={}/obj/", core::toUtf8(m_target.buildDirectory)),
        std::format("-p:DevexManagedDirectory={}", core::toUtf8(m_managedDirectory)),
        std::format("-p:DevexGeneratedDirectory={}", core::toUtf8(m_target.generatedDirectory)),
        "--nologo",
    };
    core::Result<platform::Process> process = platform::Process::start(arguments, m_project.root);
    if (!process)
    {
        m_state = State::Failed;
        m_message = std::format("the .NET SDK is needed to build C# code: {}", process.error().message);
        DEVEX_LOG_ERROR("Cannot build the C# code: {}", m_message);
        return;
    }
    m_process = std::move(*process);
    m_state = State::Building;
    m_message.clear();
    m_diagnostics.clear();
    m_buildStart = Clock::now();
    DEVEX_LOG_INFO("Building the C# code...");
}

void ManagedCodeBuilder::finishBuild(int exitCode)
{
    const double seconds = std::chrono::duration<double>(Clock::now() - m_buildStart).count();
    if (exitCode == 0)
    {
        m_state = State::Succeeded;
        m_message = std::format("built in {:.1f} s", seconds);
        DEVEX_LOG_INFO("C# code built in {:.1f} s", seconds);
        return;
    }
    m_state = State::Failed;
    if (m_message.empty())
    {
        m_message = std::format("the build failed with code {}", exitCode);
    }
    DEVEX_LOG_ERROR("C# build failed: see the errors above");
}

} // namespace devex::runtime::detail
