"""Generates the C# enumerations that mirror engine headers.

Run from any directory after changing the headers:

    python scripts/generate_managed_bindings.py
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
KEY_HEADER = ROOT / "engine" / "include" / "devex" / "platform" / "Key.hpp"
KEY_OUTPUT = ROOT / "managed" / "Devex.Managed" / "Key.cs"

HEADER = """// Generated by scripts/generate_managed_bindings.py from engine/include/devex/platform/Key.hpp.
// Do not edit: run the script again after changing the header.

namespace Devex;

/// <summary>A physical key, named after its position on a US QWERTY keyboard: Key.W is the key
/// labelled Z on AZERTY. The values are USB HID keyboard usages, like the engine's.</summary>
public enum Key
{
"""


def main():
    text = KEY_HEADER.read_text(encoding="utf-8")
    body = text[text.index("enum class Key"):]
    body = body[body.index("{") + 1:body.index("};")]
    lines = [HEADER]
    for name, value in re.findall(r"^\s*(\w+)\s*=\s*(\d+),", body, re.MULTILINE):
        lines.append(f"    {name} = {value},\n")
    lines.append("}\n")
    KEY_OUTPUT.write_text("".join(lines), encoding="utf-8", newline="\n")
    print("wrote", KEY_OUTPUT.relative_to(ROOT))


if __name__ == "__main__":
    main()
