#pragma once

#include <devex/math/Math.hpp>
#include <devex/platform/Key.hpp>
#include <devex/platform/Window.hpp>

#include <string>
#include <variant>

namespace devex::platform {

// The operating system asks the application to quit.
struct QuitRequested
{
};

struct WindowCloseRequested
{
    WindowId window;
};

// Sent when the drawable size in pixels changes.
struct WindowResized
{
    WindowId window;
    math::Extent2D size;
    math::Extent2D pixelSize;
};

struct WindowMinimized
{
    WindowId window;
};

struct WindowRestored
{
    WindowId window;
};

struct WindowFocusChanged
{
    WindowId window;
    bool focused = false;
};

struct KeyPressed
{
    Key key = Key::Unknown;
    // True when generated by the operating system's key repeat while the key is held.
    bool repeat = false;
};

struct KeyReleased
{
    Key key = Key::Unknown;
};

struct MouseButtonPressed
{
    MouseButton button = MouseButton::Left;
    math::Vec2 position{0.0f};
};

struct MouseButtonReleased
{
    MouseButton button = MouseButton::Left;
    math::Vec2 position{0.0f};
};

struct MouseMoved
{
    math::Vec2 position{0.0f};
    math::Vec2 delta{0.0f};
};

struct MouseWheelScrolled
{
    math::Vec2 delta{0.0f};
};

struct FileDropped
{
    WindowId window;
    std::string path;
};

using Event = std::variant<QuitRequested, WindowCloseRequested, WindowResized, WindowMinimized,
                           WindowRestored, WindowFocusChanged, KeyPressed, KeyReleased,
                           MouseButtonPressed, MouseButtonReleased, MouseMoved,
                           MouseWheelScrolled, FileDropped>;

} // namespace devex::platform
