#pragma once

#include <devex/core/Export.hpp>

#include <devex/math/Math.hpp>
#include <devex/platform/Key.hpp>
#include <devex/platform/Window.hpp>

#include <string>
#include <variant>

namespace devex::platform {

// The operating system asks the application to quit.
struct DEVEX_API QuitRequested
{
};

struct DEVEX_API WindowCloseRequested
{
    WindowId window;
};

// Sent when the drawable size in pixels changes.
struct DEVEX_API WindowResized
{
    WindowId window;
    math::Extent2D size;
    math::Extent2D pixelSize;
};

struct DEVEX_API WindowMinimized
{
    WindowId window;
};

struct DEVEX_API WindowRestored
{
    WindowId window;
};

struct DEVEX_API WindowFocusChanged
{
    WindowId window;
    bool focused = false;
};

struct DEVEX_API KeyPressed
{
    Key key = Key::Unknown;
    // True when generated by the operating system's key repeat while the key is held.
    bool repeat = false;
};

struct DEVEX_API KeyReleased
{
    Key key = Key::Unknown;
};

struct DEVEX_API MouseButtonPressed
{
    MouseButton button = MouseButton::Left;
    math::Vec2 position{0.0f};
};

struct DEVEX_API MouseButtonReleased
{
    MouseButton button = MouseButton::Left;
    math::Vec2 position{0.0f};
};

struct DEVEX_API MouseMoved
{
    math::Vec2 position{0.0f};
    math::Vec2 delta{0.0f};
};

struct DEVEX_API MouseWheelScrolled
{
    math::Vec2 delta{0.0f};
};

struct DEVEX_API FileDropped
{
    WindowId window;
    std::string path;
};

using Event = std::variant<QuitRequested, WindowCloseRequested, WindowResized, WindowMinimized,
                           WindowRestored, WindowFocusChanged, KeyPressed, KeyReleased,
                           MouseButtonPressed, MouseButtonReleased, MouseMoved,
                           MouseWheelScrolled, FileDropped>;

} // namespace devex::platform
