#include <devex/scene/ParticleComponents.hpp>

namespace devex::scene {

DEVEX_REFLECT(ParticleEmitter)
{
    type.field("play_on_start", &ParticleEmitter::playOnStart, {.group = "Emitter"})
        .field("looping", &ParticleEmitter::looping)
        .field("duration", &ParticleEmitter::duration)
        .field("prewarm", &ParticleEmitter::prewarm)
        .field("max_particles", &ParticleEmitter::maxParticles)
        .field("space", &ParticleEmitter::space)
        .field("seed", &ParticleEmitter::seed)
        .field("rate", &ParticleEmitter::rate, {.group = "Emission"})
        .field("rate_over_distance", &ParticleEmitter::rateOverDistance)
        .field("burst", &ParticleEmitter::burst)
        .field("shape", &ParticleEmitter::shape, {.group = "Shape"})
        .field("radius", &ParticleEmitter::radius)
        .field("angle", &ParticleEmitter::angle, {.angle = true})
        .field("box_size", &ParticleEmitter::boxSize)
        .field("from_shell", &ParticleEmitter::fromShell)
        .field("random_direction", &ParticleEmitter::randomDirection)
        .field("lifetime", &ParticleEmitter::lifetime, {.group = "Particles"})
        .field("speed", &ParticleEmitter::speed)
        .field("size", &ParticleEmitter::size)
        .field("rotation", &ParticleEmitter::rotation)
        .field("spin", &ParticleEmitter::spin)
        .field("color", &ParticleEmitter::color, {.color = true})
        .field("end_color", &ParticleEmitter::endColor, {.color = true})
        .field("intensity", &ParticleEmitter::intensity)
        .field("gravity", &ParticleEmitter::gravity, {.group = "Motion"})
        .field("acceleration", &ParticleEmitter::acceleration)
        .field("drag", &ParticleEmitter::drag)
        .field("inherit_velocity", &ParticleEmitter::inheritVelocity)
        .field("noise", &ParticleEmitter::noise)
        .field("noise_frequency", &ParticleEmitter::noiseFrequency)
        .field("noise_speed", &ParticleEmitter::noiseSpeed)
        .field("size_curve", &ParticleEmitter::sizeCurve, {.assetType = "curve", .group = "Over Life"})
        .field("alpha_curve", &ParticleEmitter::alphaCurve, {.assetType = "curve"})
        .field("speed_curve", &ParticleEmitter::speedCurve, {.assetType = "curve"})
        .field("collide", &ParticleEmitter::collide, {.group = "Collision"})
        .field("bounce", &ParticleEmitter::bounce)
        .field("friction", &ParticleEmitter::friction)
        .field("lifetime_loss", &ParticleEmitter::lifetimeLoss)
        .field("sub_emitter", &ParticleEmitter::subEmitter, {.group = "Sub Emitter"})
        .field("sub_emit_on", &ParticleEmitter::subEmitOn)
        .field("sub_emit_count", &ParticleEmitter::subEmitCount)
        .field("texture", &ParticleEmitter::texture, {.assetType = "texture", .group = "Rendering"})
        .field("material", &ParticleEmitter::material, {.assetType = "material"})
        .field("blend", &ParticleEmitter::blend)
        .field("render_mode", &ParticleEmitter::renderMode)
        .field("stretch", &ParticleEmitter::stretch)
        .field("sheet_columns", &ParticleEmitter::sheetColumns)
        .field("sheet_rows", &ParticleEmitter::sheetRows)
        .field("sheet_cycles", &ParticleEmitter::sheetCycles)
        .field("random_frame", &ParticleEmitter::randomFrame)
        .field("lit", &ParticleEmitter::lit)
        .field("softness", &ParticleEmitter::softness)
        .field("trails", &ParticleEmitter::trails, {.group = "Trails"})
        .field("trail_time", &ParticleEmitter::trailTime)
        .field("trail_width", &ParticleEmitter::trailWidth);
}

DEVEX_REFLECT(TrailRenderer)
{
    type.field("emitting", &TrailRenderer::emitting)
        .field("time", &TrailRenderer::time)
        .field("min_distance", &TrailRenderer::minDistance)
        .field("width", &TrailRenderer::width)
        .field("end_width", &TrailRenderer::endWidth)
        .field("color", &TrailRenderer::color, {.color = true})
        .field("end_color", &TrailRenderer::endColor, {.color = true})
        .field("intensity", &TrailRenderer::intensity)
        .field("texture", &TrailRenderer::texture, {.assetType = "texture"})
        .field("blend", &TrailRenderer::blend)
        .field("lit", &TrailRenderer::lit)
        .field("softness", &TrailRenderer::softness);
}

} // namespace devex::scene
